### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by MannanAnxari** [sizzlingkenny/filmato-2embed-movie-script-php#3]
hi bro i need some help in downloading the imdbthumbs images how can i download all the images of all movies ? please help me!

**Comment by TheFilthyFrog** [comment]
the thumbs are pulled from TMDB (https://developer.themoviedb.org/docs) you need to get your own API

**Comment by sizzlingkenny** [comment]
> hi bro i need some help in downloading the imdbthumbs images how can i download all the images of all movies ? please help me!

Its very simple to get images from tMDB (themoviedb.org) and if you want to host all the images on your own server by downloading them, then you have to go through the long coding process which you can learn from here "https://simplehtmldom.sourceforge.io/docs/1.9/index.html"

**Comment by MannanAnxari** [comment]
Do you have code for the process of downloading images ? 😑

**Comment by MannanAnxari** [comment]
Coz i don't know which site have the thumbs is the imdb.com or tmdb.com i dont know 😑

**Comment by MannanAnxari** [comment]
I have done bro thanks for helping 🌟
