### ISSUE TITLE
How to integrate this on Dooplay with auto-embed?

### ISSUE THREAD

**Issue by Digital-XxX** [sizzlingkenny/filmato-2embed-movie-script-php#5]
I have Dooplay with auto-embed functions but not all of them has video source. Is it possible to integrate this?

**Comment by sizzlingkenny** [comment]
I'm getting lots of queries about Dooplay, since never worked with wordpress things, but can be checked and give it a try to add our source to dooplay theme, but for that I need your cooperation, lets talk to s.k.y.p.e give me your ID we'll talk there
