### ISSUE TITLE
How can integrate this with mobile app ?

### ISSUE THREAD

**Issue by Abdulazeez-Raja** [sizzlingkenny/filmato-2embed-movie-script-php#7]

**Comment by sizzlingkenny** [comment]
We are launching an automated streaming service very soon, comes with tons of movies, tv-series, anime all together in one place to stream, and you can have the complete database and ready website in just 5 minutes, and that would be mobile devices friendly, you can convert your web-url into mobile app by using any service eg: kodular or makeroid so just tuned on this repo.

**Comment by Abdulazeez-Raja** [comment]
Is there any way else the web app ? Like if you  can provide api with monthly subscription ?

**Comment by sizzlingkenny** [comment]
come talk to me on sk.y.pe, give your id

**Comment by Abdulazeez-Raja** [comment]
I don't have sk.y.pe do you have whats.app or anything else

**Comment by sizzlingkenny** [comment]
telegram

**Comment by sizzlingkenny** [comment]
install sk.yp.e its free and easy to use

**Comment by Abdulazeez-Raja** [comment]
@azeeziq

**Comment by sizzlingkenny** [comment]
> @azeeziq

sent msg on telegrm

**Comment by Abdulazeez-Raja** [comment]
> > @azeeziq
> 
> 
> 
> sent msg on telegrm

I didn't receive anything yet on telegram

**Comment by sizzlingkenny** [comment]
> > @azeeziq
> 
> sent msg on telegrm

@sizzlingkenny
