### ISSUE TITLE
Previous repositories

### ISSUE THREAD

**Issue by prdraco** [sizzlingkenny/filmato-2embed-movie-script-php#8]
Hi. Can you please send that anime data.json file to me?
sizzlingkenny/gogoanime-api-with-data-to-embed/main/data.json
Would be great to continue it. There was more than 8k array count. Robert
robertpadar@gmail.com

**Comment by sizzlingkenny** [comment]
Hi, Robert, that project is discontinued and data was deleted, you can add your domains to our new application called autostream with automatic, movies, tv-series and anime everything is ready to use at https://autostream.skin/ or if you want just an anime site without movies and series then stay in touch we are launching stand alone anime site with data soon
